version: 2.1

orbs:
  node: circleci/node@5.0.3

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - functions
            - .firebaserc
            - firebase.json

  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Firebase
          command: npx firebase-tools@latest deploy --token $FIREBASE_TOKEN
